In [52]:
# coding:utf-8

import pandas as pd
import matplotlib.pyplot as plt
from qdata.baidu_index import get_search_index
# from qdata.baidu_index.common import check_keywords_exists
# from qdata.baidu_login import get_cookie_by_qr_login
from Util import read_json

cookie = read_json('config.json')['baidu_cookie']
keywords_list = [['发烧'],['旅游']]

In [53]:
dt = get_search_index(keywords_list=keywords_list, start_date='2023-01-01', end_date='2024-01-10', cookies=cookie)

In [54]:
df = pd.DataFrame(list(dt))

In [55]:
df = df[df['type']=='all']

In [56]:
df.head()

  keyword type        date index
0    [发烧]  all  2023-01-01  5559
1    [发烧]  all  2023-01-02  5100
2    [发烧]  all  2023-01-03  4480
3    [发烧]  all  2023-01-04  4045
4    [发烧]  all  2023-01-05  3482

In [38]:
df['num']=pd.to_numeric(df['index'])
df.reset_index(inplace=True)

In [39]:
df.head()

   level_0 keyword type        date index   num
0        0    [发烧]  all  2023-01-01  5559  5559
1        1    [发烧]  all  2023-01-02  5100  5100
2        2    [发烧]  all  2023-01-03  4480  4480
3        3    [发烧]  all  2023-01-04  4045  4045
4        4    [发烧]  all  2023-01-05  3482  3482

In [40]:
plt.figure(figsize=(9, 5))
plt.plot(df['date'], df['num'])
plt.xlabel('date')
plt.ylabel('indexes')
plt.savefig('baidu_index2.png', facecolor='w')
plt.close()

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   level_0  375 non-null    int64
 1   keyword  375 non-null    object
 2   type     375 non-null    object
 3   date     375 non-null    object
 4   index    375 non-null    object
 5   num      375 non-null    int64
dtypes: int64(2), object(4)
memory usage: 17.7+ KB

In [45]:
df['dtm'] = pd.to_datetime(df['date'])

In [46]:
plt.figure(figsize=(9, 9))
plt.plot(df['dtm'], df['num'])
plt.xlabel('date')
plt.ylabel('indexes')
plt.savefig('baidu_index1.png')
plt.close()